import type { Metadata } from 'next'
import { Poppins, Roboto } from 'next/font/google'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'

const inter = Poppins({
    weight: ['100', '300', '400', '500', '700', '900'],
    display: 'swap',
    variable: '--font-poppins',
})

const roboto = Roboto({
    display: 'swap',
    weight: ['100', '300', '400', '500', '700', '900'],
    variable: '--font-roboto',
})
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${roboto.variable}`}>
                <AntdRegistry>{children}</AntdRegistry>
            </body>
        </html>
    )
}
